# Generated by Django 3.1 on 2020-08-22 00:01

from django.db import migrations, models


# railsのマイグレファイル同様、テーブル作成（DBに放り込む情報）を記載
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
